module.exports = {
  PERMISSIONS_MANAGE: "PERMISSIONS_MANAGE",

  RECEPTION_VISA_DIRECTEUR: "RECEPTION_VISA_DIRECTEUR",
  RECEPTION_VISA_DAF: "RECEPTION_VISA_DAF",

  RECEPTION_CREATE: "RECEPTION_CREATE",
  RECEPTION_LIST: "RECEPTION_LIST",
  RECEPTION_GET: "RECEPTION_GET",
  RECEPTION_PDF: "RECEPTION_PDF",
  RECEPTION_UPDATE: "RECEPTION_UPDATE",
  RECEPTION_DELETE: "RECEPTION_DELETE",

  VALIDATION_LIST_PENDING: "VALIDATION_LIST_PENDING",
  VALIDATION_APPROVE: "VALIDATION_APPROVE",
  VALIDATION_REJECT: "VALIDATION_REJECT",
  VALIDATION_LIST_DONE: "VALIDATION_LIST_DONE",
  VALIDATION_GET: "VALIDATION_GET",

  PAIEMENT_CREATE: "PAIEMENT_CREATE",
  PAIEMENT_LIST: "PAIEMENT_LIST",
  PAIEMENT_GET: "PAIEMENT_GET",
  PAIEMENT_UPDATE: "PAIEMENT_UPDATE",
  PAIEMENT_DELETE: "PAIEMENT_DELETE",

  DEMANDE_CREATE: "DEMANDE_CREATE",
  DEMANDE_LIST: "DEMANDE_LIST",
  DEMANDE_PDF: "DEMANDE_PDF",
  DEMANDE_UPDATE: "DEMANDE_UPDATE",
  DEMANDE_DELETE: "DEMANDE_DELETE",
  DEMANDE_LIST_BY_DEMANDEUR: "DEMANDE_LIST_BY_DEMANDEUR",

  BON_COMMANDE_CREATE: "BON_COMMANDE_CREATE",
  BON_COMMANDE_LIST: "BON_COMMANDE_LIST",
  BON_COMMANDE_GET: "BON_COMMANDE_GET",
  BON_COMMANDE_PDF: "BON_COMMANDE_PDF",
  BON_COMMANDE_UPDATE: "BON_COMMANDE_UPDATE",
  BON_COMMANDE_CANCEL: "BON_COMMANDE_CANCEL",
  BON_COMMANDE_DELETE: "BON_COMMANDE_DELETE",
};
