module.exports = {
	DEMANDEUR: "DEMANDEUR",
	ACHETEUR: "ACHETEUR",
	ASSISTANTE_TECHNIQUE: "ASSISTANTE_TECHNIQUE",
	RESPONSABLE: "RESPONSABLE",
	DIRECTEUR: "DIRECTEUR",
	DAF: "DAF",
	DGA: "DGA",
	DG: "DG",
	COMPTABLE: "COMPTABLE",
	ADMIN: "ADMIN",
};