const P = require("../constants/permissions");

// Permission -> roles allowed to perform the action.
// Keep this small and explicit; it's easy to extend later.
module.exports = {
  // RBAC management
  [P.PERMISSIONS_MANAGE]: ["ADMIN"],

  // Admin modules
  [P.USERS_MANAGE]: ["ADMIN"],
  [P.USER_ROLES_MANAGE]: ["ADMIN"],
  [P.ROLES_MANAGE]: ["ADMIN"],
  [P.AGENTS_MANAGE]: ["ADMIN"],
  [P.DIRECTIONS_MANAGE]: ["ADMIN"],
  [P.DEPARTEMENTS_MANAGE]: ["ADMIN"],
  [P.SERVICES_MANAGE]: ["ADMIN"],
  [P.VALIDATION_FLOWS_MANAGE]: ["ADMIN"],
  [P.NOTIFICATIONS_ADMIN_CREATE]: ["ADMIN"],

  // Receptions (CRUD)
  [P.RECEPTION_CREATE]: ["DIRECTEUR", "ADMIN"],
  [P.RECEPTION_LIST]: ["DEMANDEUR", "RESPONSABLE", "DIRECTEUR", "DAF", "DGA", "DG", "COMPTABLE", "ADMIN"],
  [P.RECEPTION_GET]: ["DEMANDEUR", "RESPONSABLE", "DIRECTEUR", "DAF", "DGA", "DG", "COMPTABLE", "ADMIN"],
  [P.RECEPTION_PDF]: ["DEMANDEUR", "RESPONSABLE", "DIRECTEUR", "DAF", "DGA", "DG", "COMPTABLE", "ADMIN"],
  [P.RECEPTION_UPDATE]: ["DEMANDEUR", "COMPTABLE", "DAF", "ADMIN"],
  [P.RECEPTION_DELETE]: ["DEMANDEUR", "COMPTABLE", "DAF", "ADMIN"],

  // Visa Directeur: any director-level role should be allowed.
  [P.RECEPTION_VISA_DIRECTEUR]: ["DIRECTEUR", "ADMIN"],

  // Visa DAF: strictly finance (plus admin).
  [P.RECEPTION_VISA_DAF]: ["DAF", "ADMIN"],

  // Validation workflow
  [P.VALIDATION_LIST_PENDING]: ["RESPONSABLE", "DIRECTEUR", "DAF", "DGA", "DG", "ADMIN"],
  [P.VALIDATION_APPROVE]: ["RESPONSABLE", "DIRECTEUR", "DAF", "DGA", "DG", "ADMIN"],
  [P.VALIDATION_REJECT]: ["RESPONSABLE", "DIRECTEUR", "DAF", "DGA", "DG", "ADMIN"],
  [P.VALIDATION_RETURN_FOR_MODIFICATION]: ["RESPONSABLE", "DIRECTEUR", "DAF", "DGA", "DG", "ADMIN"],
  [P.VALIDATION_LIST_DONE]: ["RESPONSABLE", "DIRECTEUR", "DAF", "DGA", "DG", "ADMIN"],
  [P.VALIDATION_GET]: ["RESPONSABLE", "DIRECTEUR", "DAF", "DGA", "DG", "ADMIN"],

  // Payments
  [P.PAIEMENT_CREATE]: ["DAF", "COMPTABLE", "CAISSE", "ADMIN"],
  [P.PAIEMENT_LIST]: ["DAF", "COMPTABLE", "CAISSE", "ADMIN"],
  [P.PAIEMENT_GET]: ["DAF", "COMPTABLE", "CAISSE", "ADMIN"],
  [P.PAIEMENT_UPDATE]: ["DAF", "COMPTABLE", "CAISSE", "ADMIN"],
  [P.PAIEMENT_DELETE]: ["DAF", "COMPTABLE", "CAISSE", "ADMIN"],

  // Demandes
  [P.DEMANDE_CREATE]: ["DEMANDEUR", "RESPONSABLE", "DIRECTEUR", "DAF", "DGA", "DG", "COMPTABLE", "ADMIN"],
  [P.DEMANDE_LIST]: ["DEMANDEUR", "ASSISTANTE_TECHNIQUE", "RESPONSABLE", "DIRECTEUR", "DAF", "DGA", "DG", "COMPTABLE", "CAISSE", "ADMIN"],
  [P.DEMANDE_PDF]: ["DEMANDEUR", "ASSISTANTE_TECHNIQUE", "RESPONSABLE", "DIRECTEUR", "DAF", "DGA", "DG", "COMPTABLE", "CAISSE", "ADMIN"],
  [P.DEMANDE_UPDATE]: ["DEMANDEUR", "ADMIN"],
  [P.DEMANDE_DELETE]: ["DEMANDEUR", "ADMIN"],
  [P.DEMANDE_LIST_BY_DEMANDEUR]: ["ADMIN"],

  // Bons de commande
  [P.BON_COMMANDE_CREATE]: ["DEMANDEUR", "RESPONSABLE", "DIRECTEUR", "DAF", "DGA", "DG", "ADMIN"],
  [P.BON_COMMANDE_LIST]: ["DEMANDEUR", "RESPONSABLE", "DIRECTEUR", "DAF", "DGA", "DG", "ADMIN"],
  [P.BON_COMMANDE_GET]: ["DEMANDEUR", "RESPONSABLE", "DIRECTEUR", "DAF", "DGA", "DG", "ADMIN"],
  [P.BON_COMMANDE_PDF]: ["DEMANDEUR", "RESPONSABLE", "DIRECTEUR", "DAF", "DGA", "DG", "ADMIN"],
  [P.BON_COMMANDE_UPDATE]: ["RESPONSABLE", "DIRECTEUR", "DAF", "DGA", "DG", "ADMIN"],
  [P.BON_COMMANDE_CANCEL]: ["DAF", "DGA", "DG", "ADMIN"],
  [P.BON_COMMANDE_DELETE]: ["ADMIN"],
};
